const types = {
  DARK_THEME: 'DARK_THEME',
  LIGHT_THEME: 'LIGHT_THEME',
  SET_LOADER: 'SET_LOADER',
  STOP_LOADER: 'STOP_LOADER',
  SET_USER: 'SET_USER',
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  OPEN_TASKS: 'OPEN_TASKS',
  CLOSE_TASKS: 'CLOSE_TASKS',
  OPEN_CALENDAR: 'OPEN_CALENDAR',
  CLOSE_CALENDAR: 'CLOSE_CALENDAR',
  OPEN_USER_SETTINGS: 'OPEN_USER_SETTINGS',
  CLOSE_USER_SETTINGS: 'CLOSE_USER_SETTINGS',
  ADD_TASK: 'ADD_TASK',
  SET_TASKS: 'SET_TASKS',
  EDIT_TASK: 'EDIT_TASK',
  COMPLETE_TASK: 'COMPLETE_TASK',
  UNCOMPLETE_TASK: 'UNCOMPLETE_TASK',
  REMOVE_TASK: 'REMOVE_TASK',
}

export default types